# Generated by Django 6.0 on 2026-02-23 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('force_password_change', models.BooleanField(default=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('allow_multiple_sessions', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auth_credential',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.CharField(blank=True, max_length=500)),
                ('attempt_type', models.CharField(choices=[('success', 'Exitoso'), ('invalid_password', 'Contraseña inválida'), ('user_not_found', 'Usuario no encontrado'), ('user_inactive', 'Usuario inactivo'), ('password_expired', 'Contraseña expirada'), ('locked', 'Cuenta bloqueada'), ('force_password_change', 'Cambio de contraseña requerido'), ('other', 'Otro error')], default='other', max_length=30)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('attempted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('error_message', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'auth_loginattempt',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('logout', 'Cerrado'), ('expired', 'Expirado')], default='active', max_length=20)),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('jwt_token_hash', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'auth_loginsession',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_password', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_passwordhistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('min_length', models.PositiveSmallIntegerField(default=10)),
                ('require_upper', models.BooleanField(default=True)),
                ('require_lower', models.BooleanField(default=True)),
                ('require_digit', models.BooleanField(default=True)),
                ('require_special', models.BooleanField(default=True)),
                ('expiration_days', models.PositiveSmallIntegerField(default=45)),
                ('warning_days', models.PositiveSmallIntegerField(default=4)),
                ('history_count', models.PositiveSmallIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auth_passwordpolicy',
                'ordering': ['-created_at'],
            },
        ),
    ]
