# Generated by Django 6.0 on 2026-03-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='passwordpolicy',
            old_name='active',
            new_name='is_active',
        ),
    ]
