# Generated by Django 6.0 on 2026-03-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_active_credential_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='auth_logina_usernam_c1d75b_idx',
        ),
        migrations.RenameField(
            model_name='loginattempt',
            old_name='username',
            new_name='dni',
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['dni', 'attempted_at'], name='auth_logina_dni_461adc_idx'),
        ),
    ]
