# Generated by Django 6.0 on 2026-03-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_loginattempt_auth_logina_usernam_c1d75b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='auth_logina_dni_461adc_idx',
        ),
        migrations.RenameField(
            model_name='loginattempt',
            old_name='dni',
            new_name='username',
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', 'attempted_at'], name='auth_logina_usernam_c1d75b_idx'),
        ),
    ]
