# Generated by Django 6.0 on 2026-03-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_loginattempt_auth_logina_dni_461adc_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='lock_until',
        ),
    ]
