# Generated by Django 6.0 on 2026-03-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('codigo_patrimonial', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('detalle_tecnico', models.TextField(blank=True, null=True)),
                ('empresa_id', models.IntegerField()),
                ('sede_id', models.IntegerField()),
                ('modulo_id', models.IntegerField(blank=True, null=True)),
                ('ubicacion_id', models.IntegerField(blank=True, null=True)),
                ('piso', models.SmallIntegerField(blank=True, null=True)),
                ('usuario_asignado_id', models.IntegerField(blank=True, null=True)),
                ('usuario_registra_id', models.IntegerField()),
                ('anio_adquisicion', models.SmallIntegerField(blank=True, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('numero_orden_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento_garantia', models.DateField(blank=True, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_inventario', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('corte', models.CharField(default='CSJLN', max_length=20)),
                ('estado_bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='catalogos.catestadobien')),
                ('estado_funcionamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='catalogos.catestadofuncionamiento')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='catalogos.catmarca')),
                ('motivo_baja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes', to='catalogos.catmotivobaja')),
                ('regimen_tenencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='catalogos.catregimentenencia')),
                ('tipo_bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='catalogos.cattipobien')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'db_table': 'bienes_bien',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='BienDetalleCpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('dominio_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('conectado_red', models.BooleanField(default=False)),
                ('funcion_cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('procesador_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('procesador_cantidad', models.SmallIntegerField(blank=True, null=True)),
                ('procesador_nucleos', models.SmallIntegerField(blank=True, null=True)),
                ('procesador_velocidad', models.CharField(blank=True, max_length=30, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True)),
                ('licencia_so', models.CharField(blank=True, max_length=100, null=True)),
                ('version_office', models.CharField(blank=True, max_length=50, null=True)),
                ('licencia_office', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_ram_gb', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_modulos_ram', models.SmallIntegerField(blank=True, null=True)),
                ('capacidad_disco', models.CharField(blank=True, max_length=30, null=True)),
                ('cantidad_discos', models.SmallIntegerField(blank=True, null=True)),
                ('multimedia', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_tarjeta_video', models.CharField(blank=True, max_length=100, null=True)),
                ('arquitectura_bits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catarquitecturabits')),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_cpu', to='bienes.bien')),
                ('tipo_computadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.cattipocomputadora')),
                ('tipo_disco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cattipodisco')),
            ],
            options={
                'verbose_name': 'Detalle CPU',
                'verbose_name_plural': 'Detalles CPU',
                'db_table': 'bienes_bien_detalle_cpu',
            },
        ),
        migrations.CreateModel(
            name='BienDetalleImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impresion_color', models.BooleanField(blank=True, null=True)),
                ('memoria_ram_mb', models.SmallIntegerField(blank=True, null=True)),
                ('resolucion_maxima_ppp', models.CharField(blank=True, max_length=30, null=True)),
                ('tamano_hojas_soportadas', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_duplex', models.BooleanField(blank=True, null=True)),
                ('velocidad_impresion_ppm', models.SmallIntegerField(blank=True, null=True)),
                ('conexion_red', models.BooleanField(blank=True, null=True)),
                ('alimentacion_ac', models.CharField(blank=True, max_length=20, null=True)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_impresora', to='bienes.bien')),
                ('interfaz_conexion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catinterfazconexion')),
                ('tamano_carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cattamanocarro')),
                ('tipo_impresion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.cattipoimpresion')),
            ],
            options={
                'verbose_name': 'Detalle Impresora',
                'verbose_name_plural': 'Detalles Impresora',
                'db_table': 'bienes_bien_detalle_impresora',
            },
        ),
        migrations.CreateModel(
            name='BienDetalleMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano_pulgadas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_monitor', to='bienes.bien')),
                ('tipo_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.cattipomonitor')),
            ],
            options={
                'verbose_name': 'Detalle Monitor',
                'verbose_name_plural': 'Detalles Monitor',
                'db_table': 'bienes_bien_detalle_monitor',
            },
        ),
        migrations.CreateModel(
            name='BienDetalleScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano_documentos', models.CharField(blank=True, max_length=20, null=True)),
                ('alimentador_automatico', models.BooleanField(blank=True, null=True)),
                ('metadata', models.BooleanField(blank=True, null=True)),
                ('resolucion_exploracion', models.CharField(blank=True, max_length=50, null=True)),
                ('resolucion_salida', models.CharField(blank=True, max_length=50, null=True)),
                ('alimentacion_ac', models.CharField(blank=True, max_length=20, null=True)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_scanner', to='bienes.bien')),
                ('interfaz_conexion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catinterfazconexion')),
                ('tipo_escaner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.cattipoescaner')),
            ],
            options={
                'verbose_name': 'Detalle Escáner',
                'verbose_name_plural': 'Detalles Escáner',
                'db_table': 'bienes_bien_detalle_scanner',
            },
        ),
        migrations.CreateModel(
            name='BienDetalleSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('direccion_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('cantidad_puertos_utp', models.SmallIntegerField(blank=True, null=True)),
                ('cantidad_puertos_ftp', models.SmallIntegerField(blank=True, null=True)),
                ('cantidad_puertos_fo', models.SmallIntegerField(blank=True, null=True)),
                ('cantidad_puertos_wan', models.SmallIntegerField(blank=True, null=True)),
                ('admin_software', models.BooleanField(blank=True, null=True)),
                ('velocidad_mbps', models.IntegerField(blank=True, null=True)),
                ('chasis_slots', models.SmallIntegerField(blank=True, null=True)),
                ('migracion_atm', models.BooleanField(blank=True, null=True)),
                ('soporta_vlan', models.BooleanField(blank=True, null=True)),
                ('alimentacion_ac', models.CharField(blank=True, max_length=20, null=True)),
                ('manual_incluido', models.BooleanField(blank=True, null=True)),
                ('fuente_poder', models.CharField(blank=True, max_length=100, null=True)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_switch', to='bienes.bien')),
            ],
            options={
                'verbose_name': 'Detalle Switch',
                'verbose_name_plural': 'Detalles Switch',
                'db_table': 'bienes_bien_detalle_switch',
            },
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['empresa_id'], name='bienes_bien_empresa_404e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['sede_id'], name='bienes_bien_sede_id_d5ffac_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['modulo_id'], name='bienes_bien_modulo__2c5989_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['ubicacion_id'], name='bienes_bien_ubicaci_67216f_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['usuario_asignado_id'], name='bienes_bien_usuario_208926_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['tipo_bien'], name='bienes_bien_tipo_bi_de41cb_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['estado_funcionamiento'], name='bienes_bien_estado__d1c580_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['is_active'], name='bienes_bien_is_acti_ec713f_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['codigo_patrimonial'], name='bienes_bien_codigo__c4abd9_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['numero_serie'], name='bienes_bien_numero__ad214c_idx'),
        ),
    ]
