# Generated by Django 6.0 on 2026-03-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biendetalleimpresora',
            name='direccion_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
