# Generated by Django 6.0 on 2026-03-04 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0002_biendetalleimpresora_direccion_ip'),
        ('catalogos', '0002_cattipotarjetavideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biendetallecpu',
            name='tipo_tarjeta_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.cattipotarjetavideo'),
        ),
    ]
