# Generated by Django 6.0 on 2026-03-06 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0003_alter_biendetallecpu_tipo_tarjeta_video'),
        ('catalogos', '0003_catcategoriabien'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='categoria_bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='catalogos.catcategoriabien'),
        ),
    ]
