# Generated by Django 6.0 on 2026-03-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0004_bien_categoria_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='codigo_patrimonial',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bien',
            name='numero_serie',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
