# Generated by Django 6.0 on 2026-02-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_tipoubicacion_ubicacion_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_dni_287748_idx',
        ),
        migrations.AddField(
            model_name='bdempleados',
            name='empresa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='sedes',
            field=models.ManyToManyField(related_name='usuarios', to='locations.sede'),
        ),
    ]
