# Generated by Django 6.0 on 2026-03-07 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_empresa_sede_empresa_and_more'),
        ('users', '0004_alter_user_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='locations.modulo'),
        ),
    ]
