# Generated by Django 6.0 on 2026-03-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatTipoTarjetaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarjeta de Video',
                'verbose_name_plural': 'Tipos de Tarjeta de Video',
                'db_table': 'bienes_cat_tipo_tarjeta_video',
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
    ]
