# Generated by Django 6.0 on 2026-03-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_catcategoriabien'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatMotivoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo de mantenimiento',
                'verbose_name_plural': 'Motivos de mantenimiento',
                'db_table': 'bienes_cat_motivo_mantenimiento',
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
    ]
