# Generated by Django 6.0 on 2026-03-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bienes', '0001_initial'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('TRASLADO_SEDE', 'Traslado entre Sedes'), ('ASIGNACION_INTERNA', 'Asignación Interna')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario_origen_id', models.IntegerField()),
                ('sede_origen_id', models.IntegerField()),
                ('modulo_origen_id', models.IntegerField(blank=True, null=True)),
                ('usuario_destino_id', models.IntegerField()),
                ('sede_destino_id', models.IntegerField()),
                ('modulo_destino_id', models.IntegerField(blank=True, null=True)),
                ('ubicacion_destino_id', models.IntegerField(blank=True, null=True)),
                ('piso_destino', models.SmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('ATENDIDO', 'Atendido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_APROBACION', max_length=25)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('detalle_cancelacion', models.TextField(blank=True, null=True)),
                ('motivo_devolucion', models.TextField(blank=True, null=True)),
                ('aprobado_por_adminsede_id', models.IntegerField(blank=True, null=True)),
                ('fecha_aprobacion_adminsede', models.DateTimeField(blank=True, null=True)),
                ('aprobado_segur_salida_id', models.IntegerField(blank=True, null=True)),
                ('fecha_aprobacion_segur_salida', models.DateTimeField(blank=True, null=True)),
                ('aprobado_segur_entrada_id', models.IntegerField(blank=True, null=True)),
                ('fecha_aprobacion_segur_entrada', models.DateTimeField(blank=True, null=True)),
                ('observacion_segursede', models.TextField(blank=True, null=True)),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='catalogos.catmotivotransferencia')),
                ('motivo_cancelacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_canceladas', to='catalogos.catmotivocancelacion')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'db_table': 'bienes_transferencia',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patrimonial', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=100)),
                ('tipo_bien_nombre', models.CharField(max_length=100)),
                ('marca_nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=150)),
                ('estado_bien', models.CharField(max_length=50)),
                ('estado_funcionamiento', models.CharField(max_length=50)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='bienes.bien')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='transferencias.transferencia')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalles de Transferencia',
                'db_table': 'bienes_transferencia_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['tipo'], name='bienes_tran_tipo_c1e37b_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['estado'], name='bienes_tran_estado_f28120_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['sede_origen_id'], name='bienes_tran_sede_or_f0dd16_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['sede_destino_id'], name='bienes_tran_sede_de_bf8f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['usuario_destino_id'], name='bienes_tran_usuario_8275ec_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['fecha_registro'], name='bienes_tran_fecha_r_8d0ddc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transferenciadetalle',
            unique_together={('transferencia', 'bien')},
        ),
    ]
