# Generated by Django 6.0 on 2026-03-07 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_aprobador', models.CharField(choices=[('ADMINSEDE', 'Administrador de Sede'), ('SEGUR_SALIDA', 'Seguridad Salida'), ('SEGUR_ENTRADA', 'Seguridad Entrada')], max_length=20)),
                ('accion', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('DEVUELTO', 'Devuelto')], max_length=10)),
                ('usuario_id', models.IntegerField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='transferencias.transferencia')),
            ],
            options={
                'verbose_name': 'Aprobación de Transferencia',
                'db_table': 'bienes_transferencia_aprobacion',
                'ordering': ['fecha'],
            },
        ),
    ]
