# Generated by Django 6.0 on 2026-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0002_transferenciaaprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciaaprobacion',
            name='rol_aprobador',
            field=models.CharField(choices=[('COORDSISTEMA', 'Coordinador de Sistemas'), ('ADMINSEDE', 'Administrador de Sede'), ('SEGUR_SALIDA', 'Seguridad Salida'), ('SEGUR_ENTRADA', 'Seguridad Entrada'), ('REGISTRADOR', 'Registrador')], max_length=20),
        ),
    ]
