# Generated by Django 6.0 on 2026-03-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0003_alter_transferenciaaprobacion_rol_aprobador'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='aprobado_retorno_entrada_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='aprobado_retorno_salida_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='fecha_aprobacion_retorno_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='fecha_aprobacion_retorno_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('EN_RETORNO', 'En Retorno a Sede Origen'), ('ATENDIDO', 'Atendido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_APROBACION', max_length=25),
        ),
        migrations.AlterField(
            model_name='transferenciaaprobacion',
            name='rol_aprobador',
            field=models.CharField(choices=[('COORDSISTEMA', 'Coordinador de Sistemas'), ('ADMINSEDE', 'Administrador de Sede'), ('SEGUR_SALIDA', 'Seguridad Salida'), ('SEGUR_ENTRADA', 'Seguridad Entrada'), ('REGISTRADOR', 'Registrador'), ('SEGUR_RETORNO_SALIDA', 'Seguridad Retorno Salida'), ('SEGUR_RETORNO_ENTRADA', 'Seguridad Retorno Entrada')], max_length=200),
        ),
    ]
