# Generated by Django 6.0 on 2026-03-08 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_catcategoriabien'),
        ('transferencias', '0004_transferencia_aprobado_retorno_entrada_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferenciaaprobacion',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterModelOptions(
            name='transferenciadetalle',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='transferencia',
            name='bienes_tran_fecha_r_8d0ddc_idx',
        ),
        migrations.RemoveField(
            model_name='transferenciadetalle',
            name='estado_bien',
        ),
        migrations.RemoveField(
            model_name='transferenciadetalle',
            name='estado_funcionamiento',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='confirmado_por_usuario_destino_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='fecha_confirmacion_destino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='fecha_pdf',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='pdf_firmado_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('EN_ESPERA_CONFORMIDAD', 'En Espera de Conformidad del Destinatario'), ('EN_RETORNO', 'En Retorno a Sede Origen'), ('ATENDIDO', 'Atendido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_APROBACION', max_length=25),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='catalogos.catmotivotransferencia'),
        ),
        migrations.AlterField(
            model_name='transferenciaaprobacion',
            name='rol_aprobador',
            field=models.CharField(choices=[('COORDSISTEMA', 'Coordinador de Sistemas'), ('ADMINSEDE', 'Administrador de Sede'), ('SEGUR_SALIDA', 'Seguridad Salida'), ('SEGUR_ENTRADA', 'Seguridad Entrada'), ('SEGUR_RETORNO_SALIDA', 'Seguridad Retorno Salida'), ('SEGUR_RETORNO_ENTRADA', 'Seguridad Retorno Entrada'), ('USUARIO_DESTINO', 'Usuario Destinatario'), ('REGISTRADOR', 'Registrador')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transferenciadetalle',
            name='marca_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transferenciadetalle',
            name='modelo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transferenciadetalle',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['usuario_origen_id'], name='bienes_tran_usuario_84a934_idx'),
        ),
    ]
