# Generated by Django 6.0 on 2026-03-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0005_alter_transferenciaaprobacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='piso_origen',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='ubicacion_origen_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
