# Generated by Django 6.0 on 2026-03-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0006_transferencia_piso_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciadetalle',
            name='categoria_bien_nombre',
            field=models.CharField(default='INFORMÁTICO', max_length=100),
            preserve_default=False,
        ),
    ]
