# Generated by Django 6.0 on 2026-03-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_catmotivomantenimiento'),
        ('transferencias', '0007_transferenciadetalle_categoria_bien_nombre'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transferencia',
            name='bienes_tran_estado_f28120_idx',
        ),
        migrations.RenameField(
            model_name='transferencia',
            old_name='estado',
            new_name='estado_transferencia',
        ),
        migrations.RenameField(
            model_name='transferencia',
            old_name='motivo',
            new_name='motivo_transferencia',
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['estado_transferencia'], name='bienes_tran_estado__bc6f9e_idx'),
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='motivo_devolucion',
        ),
    ]
