# Generated by Django 6.0 on 2026-03-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0008_remove_transferencia_bienes_tran_estado_f28120_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='motivo_devolucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
