# Generated by Django 6.0 on 2026-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0009_transferencia_motivo_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='estado_transferencia',
            field=models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('EN_ESPERA_CONFORMIDAD', 'En Espera de Conformidad del Destinatario'), ('EN_RETORNO', 'En Retorno a Sede Origen'), ('EN_ESPERA_FIRMA', 'En Espera de Firma del Documento'), ('ATENDIDO', 'Atendido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_APROBACION', max_length=25),
        ),
    ]
