# Generated by Django 6.0 on 2026-04-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0010_alter_transferencia_estado_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciaaprobacion',
            name='accion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
