# Generated by Django 6.0 on 2026-02-27 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincia',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='locations.departamento'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='locations.provincia'),
        ),
        migrations.AddField(
            model_name='sede',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sede',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes', to='locations.distrito'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='modulo',
            index=models.Index(fields=['is_active'], name='locations_m_is_acti_2a894a_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['codigo'], name='locations_p_codigo_dfbaff_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['is_active'], name='locations_p_is_acti_187dd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='provincia',
            unique_together={('departamento', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='distrito',
            index=models.Index(fields=['codigo'], name='locations_d_codigo_9c46a0_idx'),
        ),
        migrations.AddIndex(
            model_name='distrito',
            index=models.Index(fields=['is_active'], name='locations_d_is_acti_b53c85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='distrito',
            unique_together={('provincia', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='sede',
            index=models.Index(fields=['is_active'], name='locations_s_is_acti_e4b0b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('nombre',)},
        ),
    ]
