# Generated by Django 6.0 on 2026-02-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choices',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distrito',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distritos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulo',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='locations.choices'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='locations.modulo'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provincias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincia',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='locations.departamento'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='locations.provincia'),
        ),
        migrations.AddField(
            model_name='sede',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sede',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes', to='locations.distrito'),
        ),
        migrations.AddField(
            model_name='sede',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes', to='locations.empresa'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='locations.sede'),
        ),
        migrations.AddIndex(
            model_name='choices',
            index=models.Index(fields=['codigo'], name='locations_c_codigo_adf58d_idx'),
        ),
        migrations.AddIndex(
            model_name='choices',
            index=models.Index(fields=['is_active'], name='locations_c_is_acti_245d30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='choices',
            unique_together={('nombre', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['codigo'], name='locations_d_codigo_4aabc1_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['is_active'], name='locations_d_is_acti_a99ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['codigo'], name='locations_e_codigo_52c8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['is_active'], name='locations_e_is_acti_6326a9_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['is_active'], name='locations_a_is_acti_270b07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('modulo', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['codigo'], name='locations_p_codigo_dfbaff_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['is_active'], name='locations_p_is_acti_187dd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='provincia',
            unique_together={('departamento', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='distrito',
            index=models.Index(fields=['codigo'], name='locations_d_codigo_9c46a0_idx'),
        ),
        migrations.AddIndex(
            model_name='distrito',
            index=models.Index(fields=['is_active'], name='locations_d_is_acti_b53c85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='distrito',
            unique_together={('provincia', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='sede',
            index=models.Index(fields=['codigo'], name='locations_s_codigo_9df503_idx'),
        ),
        migrations.AddIndex(
            model_name='sede',
            index=models.Index(fields=['is_active'], name='locations_s_is_acti_e4b0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='modulo',
            index=models.Index(fields=['codigo'], name='locations_m_codigo__101b61_idx'),
        ),
        migrations.AddIndex(
            model_name='modulo',
            index=models.Index(fields=['is_active'], name='locations_m_is_acti_2a894a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modulo',
            unique_together={('sede', 'codigo')},
        ),
    ]
