# Generated by Django 6.0 on 2026-03-03 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nombre_corto', models.CharField(help_text='Ej: CSJLN, CSJLS, CSJLE', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ruc', models.CharField(blank=True, help_text='RUC de la institución', max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'locations_empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='sede',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes', to='locations.empresa'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nombre_corto'], name='locations_e_nombre__e98e44_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['is_active'], name='locations_e_is_acti_6326a9_idx'),
        ),
    ]
