# Generated by Django 6.0 on 2026-02-24 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='choices',
            new_name='locations_c_codigo_191e84_idx',
            old_name='locations_c_codigo_adf58d_idx',
        ),
        migrations.RenameIndex(
            model_name='choices',
            new_name='locations_c_is_acti_214e79_idx',
            old_name='locations_c_is_acti_245d30_idx',
        ),
        migrations.AlterModelTable(
            name='choices',
            table='locations_codigo',
        ),
    ]
