# Generated by Django 6.0 on 2026-02-24 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_rename_locations_c_codigo_adf58d_idx_locations_c_codigo_191e84_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juzgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations_juzgado',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='area',
            name='locations_a_is_acti_270b07_idx',
        ),
        migrations.AddField(
            model_name='juzgado',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juzgados_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juzgados', to='locations.modulo'),
        ),
        migrations.RemoveField(
            model_name='area',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='area',
            name='modulo',
        ),
        migrations.AddIndex(
            model_name='juzgado',
            index=models.Index(fields=['is_active'], name='locations_j_is_acti_350b88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='juzgado',
            unique_together={('modulo', 'nombre')},
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
