# Generated by Django 6.0 on 2026-02-24 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_juzgado_alter_area_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations_tipoubicacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations_ubicacion',
            },
        ),
        migrations.AlterUniqueTogether(
            name='choices',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='choices',
            name='locations_c_codigo_191e84_idx',
        ),
        migrations.RemoveIndex(
            model_name='choices',
            name='locations_c_is_acti_214e79_idx',
        ),
        migrations.RemoveIndex(
            model_name='empresa',
            name='locations_e_codigo_52c8ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='empresa',
            name='locations_e_is_acti_6326a9_idx',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='empresa',
        ),
        migrations.AlterUniqueTogether(
            name='juzgado',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='juzgado',
            name='locations_j_is_acti_350b88_idx',
        ),
        migrations.RemoveIndex(
            model_name='modulo',
            name='locations_m_codigo__101b61_idx',
        ),
        migrations.AlterUniqueTogether(
            name='modulo',
            unique_together={('sede',)},
        ),
        migrations.AddField(
            model_name='tipoubicacion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipoubicaciones_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='locations.modulo'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipoubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='locations.tipoubicacion'),
        ),
        migrations.RemoveField(
            model_name='choices',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='juzgado',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='juzgado',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='codigo',
        ),
        migrations.AddIndex(
            model_name='tipoubicacion',
            index=models.Index(fields=['is_active'], name='locations_t_is_acti_ea6256_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipoubicacion',
            unique_together={('nombre',)},
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['modulo'], name='locations_u_modulo__2b1b77_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['tipoubicacion'], name='locations_u_tipoubi_912d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['is_active'], name='locations_u_is_acti_1057d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('modulo', 'nombre')},
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Juzgado',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
