# Generated by Django 6.0 on 2026-02-25 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_tipoubicacion_ubicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='updated_at',
        ),
    ]
