# Generated by Django 6.0 on 2026-02-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_remove_departamento_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='created_at',
        ),
    ]
