# Generated by Django 6.0 on 2026-02-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_remove_departamento_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sede',
            name='locations_s_codigo_9df503_idx',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='codigo',
        ),
    ]
