# Generated by Django 6.0 on 2026-02-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_remove_sede_locations_s_codigo_9df503_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulo',
            unique_together=set(),
        ),
    ]
