# Generated by Django 6.0 on 2026-02-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_alter_modulo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipoubicacion',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='tipoubicacion',
            name='locations_t_is_acti_ea6256_idx',
        ),
        migrations.RemoveIndex(
            model_name='ubicacion',
            name='locations_u_tipoubi_912d7d_idx',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='tipoubicacion',
        ),
        migrations.DeleteModel(
            name='TipoUbicacion',
        ),
    ]
