# Generated by Django 6.0 on 2026-03-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bienes', '0001_initial'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('usuario_realiza_id', models.IntegerField()),
                ('sede_id', models.IntegerField()),
                ('modulo_id', models.IntegerField(blank=True, null=True)),
                ('usuario_propietario_id', models.IntegerField()),
                ('datos_iniciales', models.TextField(blank=True, null=True)),
                ('tiene_imagenes', models.BooleanField(default=False)),
                ('trabajos_realizados', models.TextField(blank=True, null=True)),
                ('diagnostico_final', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('ATENDIDO', 'Atendido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='EN_PROCESO', max_length=25)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('detalle_cancelacion', models.TextField(blank=True, null=True)),
                ('motivo_devolucion', models.TextField(blank=True, null=True)),
                ('aprobado_por_adminsede_id', models.IntegerField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_cancelados', to='catalogos.catmotivocancelacion')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'bienes_mantenimiento',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_funcionamiento_antes', models.CharField(max_length=50)),
                ('estado_funcionamiento_despues', models.CharField(blank=True, max_length=50)),
                ('codigo_patrimonial', models.CharField(max_length=50)),
                ('tipo_bien_nombre', models.CharField(max_length=100)),
                ('observacion_detalle', models.TextField(blank=True, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='bienes.bien')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mantenimientos.mantenimiento')),
            ],
            options={
                'db_table': 'bienes_mantenimiento_detalle',
            },
        ),
        migrations.CreateModel(
            name='MantenimientoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mantenimientos/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mantenimientos.mantenimiento')),
            ],
            options={
                'db_table': 'bienes_mantenimiento_imagen',
            },
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['estado'], name='bienes_mant_estado_32c08f_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['sede_id'], name='bienes_mant_sede_id_31552a_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['usuario_realiza_id'], name='bienes_mant_usuario_ca8bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['usuario_propietario_id'], name='bienes_mant_usuario_ac19b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mantenimientodetalle',
            unique_together={('mantenimiento', 'bien')},
        ),
    ]
