# Generated by Django 6.0 on 2026-03-08 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_catcategoriabien'),
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='confirmado_por_propietario_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_conformidad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_pdf',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='pdf_firmado_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('EN_ESPERA_CONFORMIDAD', 'En Espera de Conformidad del Propietario'), ('ATENDIDO', 'Atendido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='EN_PROCESO', max_length=25),
        ),
        migrations.AlterField(
            model_name='mantenimientodetalle',
            name='estado_funcionamiento_antes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_antes', to='catalogos.catestadofuncionamiento'),
        ),
        migrations.AlterField(
            model_name='mantenimientodetalle',
            name='estado_funcionamiento_despues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_despues', to='catalogos.catestadofuncionamiento'),
        ),
        migrations.AlterField(
            model_name='mantenimientoimagen',
            name='imagen',
            field=models.ImageField(upload_to='mantenimientos/imagenes/'),
        ),
        migrations.CreateModel(
            name='MantenimientoAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_aprobador', models.CharField(choices=[('ASISTSISTEMA', 'Asistente de Sistemas'), ('ADMINSEDE', 'Administrador de Sede'), ('PROPIETARIO', 'Usuario Propietario del Bien')], max_length=20)),
                ('accion', models.CharField(choices=[('APROBADO', 'Aprobado'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado'), ('CONFIRMADO', 'Confirmado por propietario')], max_length=10)),
                ('usuario_id', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='mantenimientos.mantenimiento')),
            ],
            options={
                'db_table': 'bienes_mantenimiento_aprobacion',
                'ordering': ['fecha'],
            },
        ),
    ]
