# Generated by Django 6.0 on 2026-03-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_mantenimiento_confirmado_por_propietario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientodetalle',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mantenimientodetalle',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mantenimientodetalle',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
