# Generated by Django 6.0 on 2026-03-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_catmotivomantenimiento'),
        ('mantenimientos', '0003_mantenimientodetalle_marca_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mantenimiento',
            name='bienes_mant_estado_32c08f_idx',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='estado',
            new_name='estado_mantenimiento',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha_aprobacion',
            new_name='fecha_aprobacion_adminsede',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha_conformidad',
            new_name='fecha_confirmacion_propietario',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha_inicio',
            new_name='fecha_inicio_mant',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha_termino',
            new_name='fecha_termino_mant',
        ),
        migrations.RenameField(
            model_name='mantenimientodetalle',
            old_name='estado_funcionamiento_despues',
            new_name='estado_funcionamiento_final',
        ),
        migrations.RenameField(
            model_name='mantenimientodetalle',
            old_name='estado_funcionamiento_antes',
            new_name='estado_funcionamiento_inicial',
        ),
        migrations.RemoveField(
            model_name='mantenimientodetalle',
            name='codigo_patrimonial',
        ),
        migrations.RemoveField(
            model_name='mantenimientodetalle',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='mantenimientodetalle',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='mantenimientodetalle',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='mantenimientodetalle',
            name='tipo_bien_nombre',
        ),
        migrations.AddField(
            model_name='mantenimientodetalle',
            name='diagnostico_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimientodetalle',
            name='diagnostico_inicial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimientodetalle',
            name='trabajo_realizado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimientoaprobacion',
            name='rol_aprobador',
            field=models.CharField(choices=[('ASISTSISTEMA', 'Asistente de Sistemas'), ('ADMINSEDE', 'Administrador de Sede'), ('userCorte', 'Usuario Propietario del Bien')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['estado_mantenimiento'], name='bienes_mant_estado__197957_idx'),
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='datos_iniciales',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='diagnostico_final',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='motivo_devolucion',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='trabajos_realizados',
        ),
    ]
