# Generated by Django 6.0 on 2026-03-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_catmotivomantenimiento'),
        ('mantenimientos', '0004_remove_mantenimiento_bienes_mant_estado_32c08f_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha_confirmacion_propietario',
            new_name='fecha_pdf_firmado',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='confirmado_por_propietario_id',
            new_name='subido_por_id',
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado_mantenimiento',
            field=models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado — Pendiente de Firma'), ('ATENDIDO', 'Atendido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='EN_PROCESO', max_length=25),
        ),
        migrations.AlterField(
            model_name='mantenimientoaprobacion',
            name='accion',
            field=models.CharField(choices=[('ENVIADO', 'Enviado a aprobación'), ('APROBADO', 'Aprobado'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado'), ('PDF_SUBIDO', 'PDF firmado subido')], max_length=15),
        ),
        migrations.AlterField(
            model_name='mantenimientoaprobacion',
            name='rol_aprobador',
            field=models.CharField(choices=[('ASISTSISTEMA', 'Asistente de Sistemas'), ('ADMINSEDE', 'Administrador de Sede'), ('COORDSISTEMA', 'Coordinador de Sistemas'), ('SYSADMIN', 'Administrador del Sistema')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimientodetalle',
            name='estado_funcionamiento_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_mant_final', to='catalogos.catestadofuncionamiento'),
        ),
        migrations.AlterField(
            model_name='mantenimientodetalle',
            name='estado_funcionamiento_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_mant_inicial', to='catalogos.catestadofuncionamiento'),
        ),
    ]
