# Generated by Django 6.0 on 2026-03-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0005_rename_fecha_confirmacion_propietario_mantenimiento_fecha_pdf_firmado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoaprobacion',
            name='accion',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado y derivado para actualizar data'), ('ENVIADO', 'Enviado a aprobación'), ('APROBADO', 'Aprobado — Pendiente de Firma'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado'), ('ATENDIDO', 'Atendido con PDF subido')], max_length=15),
        ),
    ]
