# Generated by Django 6.0 on 2026-04-01 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0006_alter_mantenimientoaprobacion_accion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha_aprobacion_adminsede',
            new_name='fecha_aprobacion_adminsede',
        ),
    ]
