# Generated by Django 6.0 on 2026-04-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0007_rename_fecha_aprobacion_adminsede_mantenimiento_fecha_aprobacion_adminsede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimientoimagen',
            options={'ordering': ['fecha_subida']},
        ),
        migrations.RemoveField(
            model_name='mantenimientoimagen',
            name='imagen',
        ),
        migrations.AddField(
            model_name='mantenimientoimagen',
            name='imagen_path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimientoimagen',
            name='subido_por_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
