# Generated by Django 6.0 on 2026-04-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0008_alter_mantenimientoimagen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tiene_pdf_firmado',
            field=models.BooleanField(default=False),
        ),
    ]
