# Generated by Django 6.0 on 2026-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles_permission',
                'ordering': ['module', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SYSADMIN', 'Administrador del Sistema'), ('COORDSISTEMA', 'Coordinador de Sistemas'), ('ASISTSISTEMA', 'Asistente de Sistemas'), ('ADMINSEDE', 'Administrador de Sede'), ('SEGURSEDE', 'Seguridad de Sede'), ('USUARIOCORTE', 'Usuario de Corte')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles_role',
                'ordering': ['name'],
            },
        ),
    ]
