# Generated by Django 6.0 on 2026-02-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'db_table': 'roles_role_permission',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microservice_name', models.CharField(db_index=True, max_length=100, verbose_name='Microservicio')),
                ('app_label', models.CharField(db_index=True, max_length=100, verbose_name='App label')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('codename', models.CharField(db_index=True, max_length=150, verbose_name='Codename')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'roles_permission',
                'ordering': ['microservice_name', 'app_label', 'model_name', 'codename'],
                'indexes': [models.Index(fields=['microservice_name', 'app_label'], name='roles_permi_microse_05f497_idx'), models.Index(fields=['is_active', 'microservice_name'], name='roles_permi_is_acti_40999c_idx')],
                'unique_together': {('microservice_name', 'app_label', 'codename')},
            },
        ),
    ]
