# Generated by Django 6.0 on 2026-02-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='roles.permission'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module'], name='roles_permi_module_dfd65e_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['action'], name='roles_permi_action_fd5e26_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['estado'], name='roles_permi_estado_aeb044_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('module', 'action')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='roles_role_code_0e1c76_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['estado'], name='roles_role_estado_ba9eaa_idx'),
        ),
    ]
