# Generated by Django 6.0 on 2026-03-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_informe', models.CharField(max_length=20, unique=True)),
                ('usuario_elabora_id', models.IntegerField()),
                ('sede_elabora_id', models.IntegerField()),
                ('usuario_destino_id', models.IntegerField()),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('analisis', models.TextField(blank=True, null=True)),
                ('conclusiones', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('ATENDIDO', 'Atendido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_APROBACION', max_length=25)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('detalle_cancelacion', models.TextField(blank=True, null=True)),
                ('motivo_devolucion', models.TextField(blank=True, null=True)),
                ('aprobado_por_id', models.IntegerField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_canceladas', to='catalogos.catmotivocancelacion')),
            ],
            options={
                'verbose_name': 'Baja',
                'verbose_name_plural': 'Bajas',
                'db_table': 'bienes_baja',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='BajaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bien_nombre', models.CharField(max_length=100)),
                ('marca_nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=150)),
                ('numero_serie', models.CharField(max_length=100)),
                ('codigo_patrimonial', models.CharField(max_length=50)),
                ('estado_funcionamiento', models.CharField(max_length=50)),
                ('baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bajas.baja')),
            ],
            options={
                'db_table': 'bienes_baja_detalle',
            },
        ),
    ]
