# Generated by Django 6.0 on 2026-03-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bajas', '0001_initial'),
        ('bienes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajadetalle',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas', to='bienes.bien'),
        ),
    ]
