# Generated by Django 6.0 on 2026-03-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bajas', '0002_initial'),
        ('catalogos', '0001_initial'),
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajadetalle',
            name='mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas', to='mantenimientos.mantenimiento'),
        ),
        migrations.AddField(
            model_name='bajadetalle',
            name='motivo_baja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.catmotivobaja'),
        ),
        migrations.AddIndex(
            model_name='baja',
            index=models.Index(fields=['estado'], name='bienes_baja_estado_7823d6_idx'),
        ),
        migrations.AddIndex(
            model_name='baja',
            index=models.Index(fields=['sede_elabora_id'], name='bienes_baja_sede_el_e9e2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='baja',
            index=models.Index(fields=['usuario_elabora_id'], name='bienes_baja_usuario_0cced1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bajadetalle',
            unique_together={('baja', 'bien')},
        ),
    ]
