# Generated by Django 6.0 on 2026-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0003_initial'),
        ('catalogos', '0004_catmotivomantenimiento'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='baja',
            name='bienes_baja_estado_7823d6_idx',
        ),
        migrations.RenameField(
            model_name='baja',
            old_name='aprobado_por_id',
            new_name='aprobado_por_coordsistema_id',
        ),
        migrations.AddField(
            model_name='baja',
            name='estado_baja',
            field=models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('ATENDIDO', 'Atendido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_APROBACION', max_length=25),
        ),
        migrations.AddIndex(
            model_name='baja',
            index=models.Index(fields=['estado_baja'], name='bienes_baja_estado__171eb7_idx'),
        ),
        migrations.RemoveField(
            model_name='baja',
            name='estado',
        ),
    ]
