# Generated by Django 6.0 on 2026-03-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0004_remove_baja_bienes_baja_estado_7823d6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baja',
            name='cargo_coordsistema',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='baja',
            name='cargo_destino',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='baja',
            name='cargo_elabora',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='baja',
            name='docx_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='fecha_doc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='nombre_coordsistema',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='baja',
            name='nombre_destino',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='baja',
            name='nombre_elabora',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='baja',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='sede_elabora_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bajadetalle',
            name='diagnostico_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bajadetalle',
            name='diagnostico_inicial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bajadetalle',
            name='imagenes_incluidas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bajadetalle',
            name='observacion_tecnica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bajadetalle',
            name='trabajo_realizado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baja',
            name='estado_baja',
            field=models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('ATENDIDO', 'Atendido'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_APROBACION', max_length=25),
        ),
        migrations.AlterField(
            model_name='baja',
            name='numero_informe',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='bajadetalle',
            name='codigo_patrimonial',
            field=models.CharField(blank=True, default='S/C', max_length=100),
        ),
        migrations.AlterField(
            model_name='bajadetalle',
            name='estado_funcionamiento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bajadetalle',
            name='marca_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='bajadetalle',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='bajadetalle',
            name='numero_serie',
            field=models.CharField(blank=True, default='S/N', max_length=150),
        ),
        migrations.AlterField(
            model_name='bajadetalle',
            name='tipo_bien_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='BajaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_aprobador', models.CharField(choices=[('ASISTSISTEMA', 'Asistente de Sistemas'), ('COORDSISTEMA', 'Coordinador de Sistemas'), ('SYSADMIN', 'Administrador del Sistema')], max_length=30)),
                ('accion', models.CharField(choices=[('REGISTRADO', 'Registrado y derivado para aprobación'), ('ENVIADO', 'Enviado a aprobación'), ('APROBADO', 'Aprobado'), ('ATENDIDO', 'Atendido — documento firmado subido'), ('DEVUELTO', 'Devuelto para corrección'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('usuario_id', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='bajas.baja')),
            ],
            options={
                'db_table': 'bienes_baja_aprobacion',
                'ordering': ['fecha'],
            },
        ),
    ]
