# Generated by Django 6.0 on 2026-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0005_baja_cargo_coordsistema_baja_cargo_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baja',
            name='modulo_elabora_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='modulo_elabora_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bajaaprobacion',
            name='accion',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado y derivado para aprobación'), ('ENVIADO', 'Reenviado a aprobación con correcciones'), ('APROBADO', 'Aprobado — bienes dados de baja'), ('DEVUELTO', 'Devuelto para corrección'), ('CANCELADO', 'Cancelado')], max_length=20),
        ),
    ]
