# Generated by Django 6.0 on 2026-03-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0006_baja_modulo_elabora_id_baja_modulo_elabora_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baja',
            name='fecha_pdf_firmado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='pdf_firmado_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='baja',
            name='subido_por_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bajaaprobacion',
            name='accion',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado y derivado para aprobación'), ('ENVIADO', 'Reenviado a aprobación con correcciones'), ('APROBADO', 'Aprobado — bienes dados de baja'), ('ATENDIDO', 'Atendido con PDF subido'), ('DEVUELTO', 'Devuelto para corrección'), ('CANCELADO', 'Cancelado')], max_length=20),
        ),
    ]
