# Generated by Django 6.0 on 2026-04-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0007_baja_fecha_pdf_firmado_baja_pdf_firmado_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baja',
            name='estado_baja',
            field=models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('DEVUELTO', 'Devuelto'), ('APROBADO', 'Aprobado — Pendiente de Firma'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_APROBACION', max_length=25),
        ),
    ]
