# Generated by Django 6.0 on 2026-04-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0008_alter_baja_estado_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baja',
            name='estado_baja',
            field=models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('DEVUELTO', 'Devuelto'), ('APROBADO', 'Aprobado — Pendiente de Firma'), ('EN_ESPERA_FIRMA', 'En Espera de Firma del Documento'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_APROBACION', max_length=25),
        ),
    ]
