# Generated by Django 6.0 on 2026-04-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0009_alter_baja_estado_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='baja',
            name='tiene_pdf_firmado',
            field=models.BooleanField(default=False),
        ),
    ]
